# Generated by Django 4.0.5 on 2022-08-01 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('ISBN', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('OOP', 'OOP'), ('Programming', 'Programming'), ('Business', 'Business'), ('Comics', 'Comics'), ('Self Development', 'Self Development'), ('Accounting', 'Accounting'), ('Math', 'Math'), ('Physics', 'Physics'), ('Magasine', 'Magasine'), ('Software Engineering', 'Software Engineering')], max_length=50)),
                ('desciption', models.TextField()),
                ('publisheDate', models.DateField()),
                ('author', models.CharField(max_length=50)),
                ('borrowed', models.BooleanField(default=False)),
                ('borowDate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dueDate', models.DateField(auto_now_add=True)),
                ('fine', models.IntegerField()),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BookMGT.books', verbose_name='bookFine')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookMGT.books', verbose_name='Bookfeedback')),
            ],
        ),
    ]
