# Generated by Django 4.0.5 on 2022-08-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookMGT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='category',
            field=models.CharField(choices=[('Book Lost', 'Book Lost'), ('Late Submission', 'Late Submission'), ('Book Damage', 'Book Damage')], default='Book Lost', max_length=50),
        ),
        migrations.AlterField(
            model_name='fine',
            name='fine',
            field=models.IntegerField(default=0),
        ),
    ]
